version: "3"

run: once

env:
  DOTFILES_DIR:
    sh: |
      if [ -z "$DOTFILES_DIR" ]; then
        echo "Error: DOTFILES_DIR environment variable is not set" >&2
        exit 1
      fi

tasks:
  atuin-login:
    desc: Login with Atuin
    cmds:
      - atuin login -u vl-cr

  brew:
    desc: Install Brew bundle from dotfiles
    dir: $DOTFILES_DIR/setup
    cmds:
      - brew bundle install
      - brew cleanup

  casks:
    desc: Install Brew casks from dotfiles
    dir: $DOTFILES_DIR/setup
    cmds:
      - brew bundle install --file=Brewfile-casks
      - brew cleanup
      - |
        if [ ! -f "$FIREFOX_CONFIG_PATH/Profiles/vl-cr/times.json" ]; then
          firefox -P
        fi

  snaps:
    desc: Install snaps for Ubuntu Desktop from dotfiles
    dir: $DOTFILES_DIR/setup
    cmds:
      - bash snaps.sh
      - |
        if [ ! -f "$FIREFOX_CONFIG_PATH/Profiles/vl-cr/times.json" ]; then
          firefox -P
        fi
