"$schema" = "https://starship.rs/config-schema.json"

add_newline = true
palette = "catppuccin_mocha"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold yellow)"

[git_branch]
truncation_length = 10
truncation_symbol = "~"
symbol = ""
format = " [$symbol $branch(:$remote_branch)]($style)"
style = "bold white"

[git_status]
format = ' ([\[$all_status$ahead_behind\]]($style))'
style = "bold white"

[nix_shell]
disabled = false
impure_msg = "devbox"
format = "  [$state]($style)"
style = "bold purple"

[aws]
disabled = false
symbol = ""
format = '  [$symbol ($profile)(\[$duration\])]($style)'
style = "bold yellow"

[package]
disabled = true

[python]
disabled = true
symbol = ""
format = "  [${symbol} ${pyenv_prefix}(${version})]($style)"

[kubernetes]
disabled = true

[docker_context]
disabled = true

[nodejs]
disabled = true

[dotnet]
disabled = true

[lua]
disabled = true

# https://github.com/catppuccin/starship/blob/main/themes/mocha.toml
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
