# Define Cross-Desktop Group
# $HOME/Library/Application\ Support is default on macOS
# (data is in $HOME/.local/share; cache is in $HOME/Library/Caches)
export XDG_CONFIG_HOME="$HOME/.config"

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$ZDOTDIR/.zsh_history"
