source $ZDOTDIR/aliases

# Zsh
source $HOMEBREW_PREFIX/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source $HOMEBREW_PREFIX/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
(( ${+ZSH_HIGHLIGHT_STYLES} )) || typeset -A ZSH_HIGHLIGHT_STYLES  # Remove path underline (from syntax highlighting)
ZSH_HIGHLIGHT_STYLES[path]=none
ZSH_HIGHLIGHT_STYLES[path_prefix]=none
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'  # Make completions case-insensitive
autoload -Uz compinit && compinit

bindkey -r '^D'

# Zsh History
setopt SHARE_HISTORY       # To allow all sessions to share history
setopt INC_APPEND_HISTORY  # Save zsh to history immediately after running the command
HISTSIZE=10000
SAVEHIST=10000

# Evals
source <(fzf --zsh)
eval "$(zoxide init --cmd cd zsh)"
eval "$(starship init zsh)"

# Automatically enter Zellij on shell startup only on macOS
if [[ "$OSTYPE" == "darwin"* ]]; then
  if [[ -z "$ZELLIJ" ]]; then
    zellij
  fi
fi
