source $ZDOTDIR/aliases
source $ZDOTDIR/history

# Zsh
source $HOMEBREW_PREFIX/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source $HOMEBREW_PREFIX/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
(( ${+ZSH_HIGHLIGHT_STYLES} )) || typeset -A ZSH_HIGHLIGHT_STYLES  # Remove path underline (from syntax highlighting)
ZSH_HIGHLIGHT_STYLES[path]=none
ZSH_HIGHLIGHT_STYLES[path_prefix]=none
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'  # Make completions case-insensitive
autoload -Uz compinit && compinit

# bindkey -r '^D'

# Evals
# https://github.com/junegunn/fzf?tab=readme-ov-file#respecting-gitignore
export FZF_DEFAULT_COMMAND="fd --type f --strip-cwd-prefix --hidden --follow --exclude .git"
export STARSHIP_CONFIG="$XDG_CONFIG_HOME"/starship/starship.toml

source <(fzf --zsh)
eval "$(starship init zsh)"
eval "$(zoxide init --cmd cd zsh)"

# Automatically enter Zellij on shell startup only on macOS
if [[ "$OSTYPE" == "darwin"* ]]; then
  if [[ -z "$ZELLIJ" ]]; then
    zellij
  fi
fi
