# https://yazi-rs.github.io/docs/configuration/yazi
[mgr]
ratio = [0, 4, 5]
sort_by = "natural"
sort_sensitive = false
sort_dir_first = true
sort_translit = true
show_hidden = false
show_symlink = true

[preview]
wrap = "no"
tab_size = 2
image_delay = 30
max_width = 1200
max_height = 1500
