# Taps
tap "derailed/k9s", trusted: true
tap "hashicorp/tap", trusted: true

brew "gcc"

# Core dev dependencies
brew "git"
brew "go"
brew "go-task"
brew "node@22", link: true
brew "pnpm"
brew "python@3.14", link: true
brew "tree-sitter-cli"

# Kubernetes
brew "derailed/k9s/k9s"
brew "helm"
brew "kubectl"

# Other dev dependencies
# brew "azure-cli"
# brew "awscli"
# brew "postgresql@14", link: true, restart_service: true

# CLIs
brew "atuin"
brew "bandwhich"
brew "bat"
brew "bottom"
brew "carapace"
brew "dua-cli"
brew "delta"
brew "docker"
brew "duf"
brew "eza"
brew "fastfetch"
brew "fd"
brew "fzf"
brew "gh"
brew "glow"
brew "gping"
brew "hashicorp/tap/terraform"
brew "lazydocker"
brew "lazygit"
brew "neovim"
# brew "podman"
# brew "podman-compose"
brew "poppler"
brew "rainfrog"
brew "ripgrep"
brew "sd"
brew "sheldon"
brew "starship"
brew "tealdeer"
brew "uv"
brew "watch" if OS.mac?
brew "wget"
brew "xh"
brew "yazi"
brew "yq"
brew "zellij"
brew "zoxide"
brew "zsh" if OS.linux?
