# Taps
tap "derailed/k9s"
tap "hashicorp/tap"

# Core dev dependencies
brew "gcc"
brew "git"
brew "go"
brew "go-task"
brew "node@20", link: true
brew "poetry"
brew "python@3.12", link: true

# Kubernetes
brew "derailed/k9s/k9s"
brew "helm"
brew "kubectl"

# Other dev dependencies
brew "awscli"
brew "postgresql@14", link: true, restart_service: true

# CLIs
brew "atuin"
brew "bandwhich"
brew "bat"
brew "bottom"
brew "carapace"
brew "docker"
brew "dua-cli"
brew "delta"
brew "duf"
brew "eza"
brew "fastfetch"
brew "fd"
brew "fzf"
brew "glow"
brew "gping"
brew "hashicorp/tap/terraform"
brew "lazydocker"
brew "lazygit"
brew "neovim"
brew "poppler"
brew "rainfrog"
brew "ripgrep"
brew "sd"
brew "sheldon"
brew "starship"
brew "tealdeer"
brew "uv"
brew "watch" if OS.mac?
brew "wget"
brew "xh"
brew "yazi"
brew "yq"
brew "zellij"
brew "zoxide"
brew "zsh" if OS.linux?
